
[tasks.rust]
script_runner = "@rust"
script = [
'''
//! ```cargo
//! [dependencies]
//! time = "*"
//! ```
extern crate time;
fn main() {
    println!("{}", time::now().rfc822z());
}
'''
]

[tasks.rust-simple]
script_runner = "@rust"
script = [
'''
fn main() {
    println!("test");
}
'''
]
